Repository redhat-cne/hw-event-proxy-operator, pull requests merged in 2022-06, with the labels that each got.

#37 Add required files for bundle creation
  manifests/art.yaml
  manifests/hw-event-proxy-operator.package.yaml
  manifests/image-references
Labels: approved, lgtm, needs-ok-to-test

#38 Clone manifests in manifests/stable for ART build
  manifests/stable/event.redhat-cne.org_hardwareevents.yaml
  manifests/stable/hw-event-proxy-operator-manager-config_v1_configmap.yaml
  manifests/stable/hw-event-proxy-operator-webhook-service_v1_service.yaml
  manifests/stable/hw-event-proxy-operator.clusterserviceversion.yaml
  manifests/stable/image-references
Labels: approved, lgtm, ok-to-test

#39 [ART-4075] Fix CSV path in `art.yaml`
  manifests/art.yaml
Labels: approved, lgtm, needs-ok-to-test

#42 Align kube-rbac-proxy image references
  bundle/manifests/hw-event-proxy-operator.clusterserviceversion.yaml
  config/default/manager_auth_proxy_patch.yaml
  manifests/stable/hw-event-proxy-operator.clusterserviceversion.yaml
  manifests/stable/image-references
Labels: approved, lgtm, ok-to-test

#43 Align tags for kube-rbac-proxy image references
  bundle/manifests/hw-event-proxy-operator.clusterserviceversion.yaml
  config/default/manager_auth_proxy_patch.yaml
Labels: approved, lgtm, ok-to-test

#45 Update ART files to rename operator to bare-metal-event-relay
  bundle/render_templates
  bundle/render_vars.in
  manifests/art.yaml
  manifests/bare-metal-event-relay.package.yaml
  manifests/hw-event-proxy-operator.package.yaml
  manifests/stable/bare-metal-event-relay.clusterserviceversion.yaml
Labels: approved, lgtm
